/* ============================================================
   EF EN CASA · Datos de la Programación Didáctica 2025-2026
   Educación Física · 5º de Primaria
   Laura de los Ángeles Hernández Sierra
   ------------------------------------------------------------
   NOTA: los vídeos de YouTube son PROVISIONALES (de fachada).
   Sustituye cada campo "video" por el ID del vídeo definitivo.
   El ID es lo que va después de "watch?v=" en la URL.
   ============================================================ */

// ---- Inteligencias múltiples (Gardner, 1983) ----
const INTELIGENCIAS = {
  ling:  { nombre: "Lingüístico-verbal",   emoji: "🗣️", color: "#e11d48", desc: "Aprendo hablando, leyendo y escribiendo." },
  logi:  { nombre: "Lógico-matemática",    emoji: "🔢", color: "#2563eb", desc: "Aprendo contando, midiendo y razonando." },
  espa:  { nombre: "Visual-espacial",      emoji: "🎨", color: "#9333ea", desc: "Aprendo dibujando, imaginando y grabando." },
  corp:  { nombre: "Corporal-cinestésica", emoji: "🤸", color: "#f97316", desc: "Aprendo moviéndome y haciendo con mi cuerpo." },
  musi:  { nombre: "Musical",              emoji: "🎵", color: "#0d9488", desc: "Aprendo con ritmos, canciones y melodías." },
  inter: { nombre: "Interpersonal",        emoji: "🤝", color: "#ca8a04", desc: "Aprendo en equipo, con mi familia y amistades." },
  intra: { nombre: "Intrapersonal",        emoji: "🧠", color: "#4f46e5", desc: "Aprendo conociéndome y reflexionando." },
  natu:  { nombre: "Naturalista",          emoji: "🌿", color: "#16a34a", desc: "Aprendo observando y cuidando mi entorno." },
};

// ---- Fases de la secuencia de Merrill ----
const FASES = {
  activacion:   { nombre: "Activación",   emoji: "🔥", color: "#ef4444", desc: "Conecto lo nuevo con lo que ya sé y ya vivo." },
  demostracion: { nombre: "Demostración", emoji: "👀", color: "#3b82f6", desc: "Observo ejemplos y modelos de cómo se hace." },
  aplicacion:   { nombre: "Aplicación",   emoji: "💪", color: "#f59e0b", desc: "Lo practico yo, con retos a mi medida." },
  integracion:  { nombre: "Integración",  emoji: "🚀", color: "#22c55e", desc: "Lo uso en mi vida real y lo comparto con los demás." },
};

// ---- Unidades de Programación ----
const UNIDADES = [
  /* ============ UP 1 ============ */
  {
    id: "up1",
    num: 1,
    titulo: "Y tú, ¿te cuidas?",
    emoji: "💚",
    tagline: "Hábitos saludables y expresión corporal para empezar el curso con energía.",
    trimestre: 1,
    fechas: "10 septiembre – 13 octubre",
    sesiones: 15,
    color: "#10b981",
    color2: "#0ea5e9",
    reto: "🌟 Reto de la unidad: organiza en tu casa un «Festival del Cuidado» donde enseñes a tu familia un baile canario, una coreografía urbana y tres hábitos saludables que hayas incorporado a tu semana.",
    justificacion: "Propuesta de acogida y adaptación al inicio del curso. A través de la expresión corporal promovemos la cohesión, la comunicación, la desinhibición y el bienestar emocional, mientras construimos rutinas y hábitos de vida activa y saludable.",
    criterios: ["1.1 Integrar activación corporal, autorregulación del esfuerzo, relajación e higiene en la práctica motriz.", "4.2 Crear y reproducir composiciones con o sin soporte musical, transmitiendo emociones e ideas con ritmo y movimiento."],
    saberes: ["Vida activa y saludable: cuidado del cuerpo, higiene, postura, descanso e hidratación.", "Manifestaciones de la cultura motriz: el cuerpo y el movimiento para expresar emociones.", "Diseño de actividades rítmico-musicales con carácter expresivo (tajaraste y malagueña)."],
    productos: ["Tajaraste y malagueña", "Coreografía urbana", "Tarjetas de emociones", "Mural del evento"],
    actividades: [
      {
        id: "a1", titulo: "Mi semana en movimiento", fase: "activacion", duracion: "30-40 min",
        inteligencias: ["intra", "logi"],
        video: "XqZsoesa55w",
        desc: "Antes de aprender a cuidarnos, vamos a descubrir cómo nos cuidamos AHORA. Verás un vídeo sobre hábitos saludables y después te convertirás en detective de tu propia semana: ¿cuánto te mueves?, ¿qué desayunas?, ¿a qué hora te acuestas?",
        pasos: [
          "Ve el vídeo y anota 3 ideas que te llamen la atención.",
          "Descarga o copia la tabla «Mi semana en movimiento» (días de la semana × hábitos: moverme, desayunar sano, beber agua, dormir bien, pantallas).",
          "Durante 7 días, pinta una carita 😃 😐 😴 en cada casilla según cómo lo hiciste.",
          "Al final de la semana, cuenta tus caritas y escribe: ¿en qué hábito soy un/a campeón/a? ¿Cuál necesito entrenar?",
        ],
        entrega: "Sube a Classroom una foto de tu tabla rellena y tus dos frases de conclusión.",
      },
      {
        id: "a2", titulo: "El cuerpo habla: espejo de emociones", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "intra", "inter"],
        video: "CevxZvSJLk8",
        desc: "Nuestro cuerpo dice cosas sin usar palabras. En este vídeo verás cómo la postura, los gestos y el movimiento expresan alegría, miedo, sorpresa o calma. Después jugarás al «espejo emocional» con alguien de tu casa.",
        pasos: [
          "Observa en el vídeo cómo se expresan las emociones con el cuerpo (sin hablar).",
          "Prepara 6 tarjetas de emociones: alegría, tristeza, enfado, miedo, sorpresa y calma.",
          "Juega al espejo: una persona saca una tarjeta y la representa SOLO con el cuerpo; la otra la imita como un espejo y adivina la emoción.",
          "Cambiad de rol. ¡Mínimo 3 rondas cada uno!",
        ],
        entrega: "Foto o vídeo corto (máx. 30 s) de una ronda del juego del espejo + escribe qué emoción te costó más representar y por qué.",
      },
      {
        id: "a3", titulo: "Tajaraste y malagueña paso a paso", fase: "demostracion", duracion: "40 min",
        inteligencias: ["musi", "corp"],
        video: "kJQP7kiw5Fk",
        desc: "El tajaraste y la malagueña son bailes tradicionales de Canarias, parte de nuestro patrimonio. En este vídeo verás los pasos básicos despacito y con música. Fíjate en el ritmo, la posición de los brazos y el punteo de los pies.",
        pasos: [
          "Ve el vídeo completo una vez SIN moverte, solo observando.",
          "Segunda vez: imita los pasos básicos del tajaraste (marca el ritmo con palmas primero).",
          "Tercera vez: añade los brazos y prueba la malagueña.",
          "Practica 10 minutos al día durante 3 días. ¡El baile se aprende bailando!",
        ],
        entrega: "Vídeo (máx. 1 min) bailando los pasos básicos de uno de los dos bailes. Puedes salir con familia, ¡suma puntos de estrella! ⭐",
      },
      {
        id: "a4", titulo: "Mi coreografía urbana", fase: "aplicacion", duracion: "45-60 min (en varias sesiones)",
        inteligencias: ["corp", "musi", "espa"],
        video: "OPf0YbXqDm0",
        desc: "Ahora te toca crear a ti. Con lo aprendido sobre ritmo y expresión, inventarás tu propia coreografía urbana de 4 bloques de 8 tiempos. Elige una música que te motive (¡y que sea apropiada!).",
        pasos: [
          "Elige tu canción y escúchala contando los tiempos: 1-2-3-4-5-6-7-8.",
          "Inventa 4 movimientos o pasos, uno para cada bloque de 8 tiempos.",
          "Ensaya la secuencia completa hasta encadenarla sin parar.",
          "Detalle PRO: añade un principio (pose inicial) y un final (pose congelada).",
        ],
        entrega: "Vídeo de tu coreografía completa (4×8 tiempos) con la música de fondo.",
      },
      {
        id: "a5", titulo: "Rutina saludable: activación y vuelta a la calma", fase: "aplicacion", duracion: "25 min",
        inteligencias: ["corp", "intra"],
        video: "09R8_2nJtjg",
        desc: "Todo deportista sabe que hay que calentar antes y relajarse después. Diseñarás tu propia rutina de activación (calentamiento) y de vuelta a la calma con respiración y estiramientos, para usarla en TODAS las actividades del curso.",
        pasos: [
          "Observa el vídeo con ejemplos de calentamiento y relajación.",
          "Diseña tu activación: 5 ejercicios de 30 segundos (movilidad de tobillos, rodillas, cadera, hombros y carrera suave).",
          "Diseña tu vuelta a la calma: 3 estiramientos + 1 minuto de respiración profunda (inspira 4 s, suelta 6 s).",
          "Dibuja o escribe tu rutina en una ficha con los nombres de cada ejercicio.",
        ],
        entrega: "Foto de tu ficha de rutina. La usarás como «carné de calentamiento» el resto del curso.",
      },
      {
        id: "a6", titulo: "Festival del Cuidado: mural del evento", fase: "integracion", duracion: "60 min + evento",
        inteligencias: ["inter", "ling", "espa"],
        video: "pRpeEdMmmQ0",
        desc: "¡Gran final de la unidad! Organiza en casa tu «Festival del Cuidado»: enseña a tu familia el baile canario, tu coreografía y tus 3 mejores hábitos. Después lo contarás en un mural digital compartido con toda la clase.",
        pasos: [
          "Prepara tu festival: elige el orden (baile canario → coreografía → hábitos saludables).",
          "Celebra el festival con tu familia y pide que alguien haga 2-3 fotos.",
          "Entra en el mural digital de la clase (enlace en Classroom) y crea tu publicación: 1 foto + 3 líneas contando cómo fue.",
          "Comenta con un emoji y una frase amable la publicación de al menos 2 compañeros/as. 💬",
        ],
        entrega: "Tu publicación en el mural digital de la clase + comentarios amables a 2 compañeros/as.",
      },
    ],
  },

  /* ============ UP 2 ============ */
  {
    id: "up2",
    num: 2,
    titulo: "¡Nos movemos!",
    emoji: "🏃",
    tagline: "Desplazamientos, equilibrio y coordinación… ¡con seguridad ante todo!",
    trimestre: 1,
    fechas: "15 octubre – 13 noviembre",
    sesiones: 12,
    color: "#0ea5e9",
    color2: "#6366f1",
    reto: "🌟 Reto de la unidad: conviértete en «entrenador/a personal» de tu casa: diseña un circuito de equilibrio y coordinación seguro y consigue que toda tu familia lo supere.",
    justificacion: "Desarrollamos las habilidades motrices básicas (desplazamientos, coordinación y agilidad) mediante situaciones variadas y motivadoras, mejorando el control corporal y el equilibrio de forma progresiva y lúdica, siempre aplicando medidas de seguridad.",
    criterios: ["1.2 Aplicar medidas de seguridad antes, durante y después de la práctica de actividad física.", "2.1 Aplicar principios básicos de toma de decisiones en situaciones lúdicas y juegos motores a partir de la anticipación."],
    saberes: ["Vida activa y saludable: cuidado del cuerpo e hidratación.", "Organización y gestión de la actividad física con fines lúdicos.", "Seguridad en la práctica motriz: identificación de contextos de riesgo."],
    productos: ["Circuito de equilibrio", "Los trucos", "Exposiciones", "Videomontaje"],
    actividades: [
      {
        id: "a1", titulo: "Detective del riesgo", fase: "activacion", duracion: "30 min",
        inteligencias: ["logi", "intra", "natu"],
        video: "dQw4w9WgXcQ",
        desc: "Antes de movernos, ¡aseguramos el terreno! Verás un vídeo sobre seguridad en la actividad física y luego inspeccionarás tu casa como un auténtico detective para encontrar la zona más segura para entrenar.",
        pasos: [
          "Ve el vídeo y apunta las 3 reglas de oro de la seguridad.",
          "Inspecciona tu casa: busca una zona de al menos 2×2 metros libre de obstáculos.",
          "Rellena el «Informe del detective»: ¿qué peligros encontraste? (esquinas, suelo resbaladizo, objetos frágiles…) ¿Cómo los solucionaste?",
          "Haz tu checklist personal pre-entrenamiento: espacio ✔ ropa y calzado ✔ agua ✔ aviso a la familia ✔.",
        ],
        entrega: "Foto de tu «Informe del detective» con los riesgos detectados y las soluciones.",
      },
      {
        id: "a2", titulo: "Equilibrios imposibles", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "espa"],
        video: "JGwWNGJdvx8",
        desc: "El equilibrio es la base de casi todo movimiento. En el vídeo verás equilibrios estáticos (sin moverte) y dinámicos (en movimiento) de dificultad creciente. Observa dónde ponen la mirada y los brazos: ¡ese es el secreto!",
        pasos: [
          "Ve el vídeo fijándote en 3 trucos: mirada fija, brazos abiertos, tripa apretada.",
          "Prueba los 5 equilibrios básicos: flamenco (30 s por pierna), puntillas, talones, avión y escuadra.",
          "Anota cuántos segundos aguantas en cada uno. Es tu marca inicial.",
          "Repítelos 3 días y comprueba si tu marca mejora.",
        ],
        entrega: "Tabla con tus tiempos del día 1 y del día 3 en los 5 equilibrios. ¿Mejoraste?",
      },
      {
        id: "a3", titulo: "Desplazamientos locos", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "espa"],
        video: "L_jWHffIx5E",
        desc: "Andar y correr no son las únicas formas de moverse: cuadrupedia, reptación, saltos a pata coja, desplazamientos laterales, giros… En el vídeo verás un repertorio de desplazamientos que luego imitarás con precisión.",
        pasos: [
          "Observa los desplazamientos del vídeo y elige tus 6 favoritos.",
          "Marca un recorrido corto en tu zona segura (usa cojines o botellas como referencias).",
          "Recorre el trayecto con cada uno de los 6 desplazamientos.",
          "Reto extra: hazlo con un objeto en equilibrio sobre la cabeza (¡un peluche vale!).",
        ],
        entrega: "Lista de tus 6 desplazamientos elegidos + vídeo corto (30 s) mostrando 3 de ellos.",
      },
      {
        id: "a4", titulo: "Mi circuito de equilibrio", fase: "aplicacion", duracion: "45 min",
        inteligencias: ["corp", "espa", "logi"],
        video: "9bZkp7q19f0",
        desc: "¡A diseñar! Con materiales de casa (cinta de pintor, cojines, libros, cuerda…) construirás un circuito de equilibrio de 5 estaciones. Como buen ingeniero/a del movimiento, primero lo dibujas y después lo montas.",
        pasos: [
          "Dibuja el plano de tu circuito con las 5 estaciones numeradas (ej.: línea de cinta en el suelo, camino de cojines, equilibrio del flamenco, paso del río con libros, giro y pose final).",
          "Monta el circuito revisando tu checklist de seguridad de la actividad 1.",
          "Cronométrate 3 veces. Anota tu mejor tiempo… ¡sin perder el equilibrio!",
          "Ajusta la dificultad: si es muy fácil, estrecha los apoyos; si es difícil, amplíalos (¡así se adapta un buen entrenador!).",
        ],
        entrega: "Foto del plano + foto del circuito montado + tus 3 tiempos.",
      },
      {
        id: "a5", titulo: "Los trucos: reto de coordinación", fase: "aplicacion", duracion: "20 min al día × 5 días",
        inteligencias: ["corp", "intra"],
        video: "ktvTqknDobU",
        desc: "Cada día, un truco de coordinación nuevo con material casero: pelota de calcetines, vaso de plástico, globo… La regla de oro: fallar es entrenar. Registra tus intentos y celebra tu progreso.",
        pasos: [
          "Día 1: lanza la pelota de calcetines, da una palmada y atrápala (sube palmadas: 1, 2, 3…).",
          "Día 2: mantén un globo en el aire con manos, cabeza y rodillas (cuenta los toques).",
          "Día 3: «flip» del vaso: lánzalo desde el borde de la mesa y que caiga de pie.",
          "Día 4: bota una pelota alrededor de tu cuerpo sin que se escape.",
          "Día 5: combina dos trucos seguidos e inventa el tuyo propio.",
        ],
        entrega: "Tabla de registro de los 5 días (intentos y récords) + vídeo de tu truco inventado.",
      },
      {
        id: "a6", titulo: "Videomontaje: ¡cómo nos movemos!", fase: "integracion", duracion: "60 min",
        inteligencias: ["espa", "ling", "intra"],
        video: "RgKAFK5djSk",
        desc: "Cierre de unidad: crea un mini videomontaje (1-2 min) con tus mejores momentos: el circuito, los trucos, los equilibrios… Añade rótulos con lo que aprendiste. Será tu «tráiler de superación personal».",
        pasos: [
          "Reúne los clips y fotos de las actividades anteriores.",
          "Ordénalos contando una historia: cómo empezaste → cómo entrenaste → qué lograste.",
          "Añade 3 rótulos o carteles: tu mejor marca, tu mayor dificultad y tu consejo de seguridad favorito.",
          "Expón tu vídeo a tu familia y pídeles una frase de feedback.",
        ],
        entrega: "Tu videomontaje (máx. 2 min) + la frase de feedback de tu familia.",
      },
    ],
  },

  /* ============ UP 3 ============ */
  {
    id: "up3",
    num: 3,
    titulo: "¿Superaremos estos retos?",
    emoji: "🧗",
    tagline: "Desafíos motrices de equilibrio, agilidad y control corporal.",
    trimestre: 1,
    fechas: "17 noviembre – 18 diciembre",
    sesiones: 12,
    color: "#8b5cf6",
    color2: "#ec4899",
    reto: "🌟 Reto de la unidad: supera la «Ruleta de los 12 retos» y documenta tu aventura en un videomontaje final. ¿Conseguirás los 12?",
    justificacion: "El alumnado se enfrenta a desafíos motrices que implican equilibrio, coordinación y control corporal. Con actividades lúdicas y progresivas desarrollamos las habilidades motrices, la autonomía, la superación personal y el respeto.",
    criterios: ["1.2 Aplicar medidas de seguridad antes, durante y después de la práctica de actividad física.", "2.2 Adquirir un progresivo control y dominio corporal, implementando retos motores individuales o grupales."],
    saberes: ["Prevención de lesiones: activación y vuelta a la calma, normas de seguridad.", "Resolución de problemas en situaciones motrices: reajuste instantáneo de la acción motriz."],
    productos: ["Circuito de desplazamientos", "La ruleta callejera", "Test interactivo", "Videomontaje de la experiencia"],
    actividades: [
      {
        id: "a1", titulo: "El reto de los 60 segundos", fase: "activacion", duracion: "25 min",
        inteligencias: ["corp", "logi", "intra"],
        video: "7wtfhZwyrcc",
        desc: "¿Cuánto puedes hacer en 1 minuto? Saltos, sentadillas, toques de globo, equilibrio… Mide tu punto de partida en 5 pruebas de 60 segundos. Al final de la unidad las repetirás: los datos no mienten, ¡habrás mejorado!",
        pasos: [
          "Haz tu activación (¡usa tu carné de calentamiento de la UP1!).",
          "Prueba 1: saltos con pies juntos en 60 s. Prueba 2: sentadillas. Prueba 3: toques de globo. Prueba 4: segundos en equilibrio flamenco. Prueba 5: «escalador» (rodillas al pecho en plancha).",
          "Anota tus resultados en la «Tarjeta de marcas» con la fecha.",
          "Escribe tu predicción: ¿cuánto crees que mejorarás al final de la unidad?",
        ],
        entrega: "Foto de tu Tarjeta de marcas inicial con las 5 pruebas y tu predicción.",
      },
      {
        id: "a2", titulo: "La ruleta callejera", fase: "demostracion", duracion: "35 min",
        inteligencias: ["corp", "espa"],
        video: "60ItHLz5WEA",
        desc: "Inspirado en el street workout y el parkour escolar (¡versión segura!). En el vídeo verás retos de agilidad urbanos adaptados. Después girarás tu ruleta de retos: el azar decide qué desafío entrenas hoy.",
        pasos: [
          "Ve el vídeo y fíjate en cómo apoyan manos y pies, y cómo amortiguan las caídas doblando las rodillas.",
          "Construye tu ruleta con 6 retos (dibújala en cartón o usa una app de ruleta): salto preciso, paso de gato, equilibrio en línea, giro de 180°, salto y recepción silenciosa, reptar bajo una silla.",
          "Gira la ruleta 4 veces y practica cada reto que salga (3 intentos por reto).",
          "Regla de seguridad: todo se hace a ras de suelo, nunca en altura.",
        ],
        entrega: "Foto de tu ruleta + vídeo (30 s) superando 2 de los retos que te tocaron.",
      },
      {
        id: "a3", titulo: "Cambio de dirección: agilidad ninja", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "logi"],
        video: "fJ9rUzIMcZQ",
        desc: "La agilidad es cambiar de dirección rápido SIN perder el control. Observa en el vídeo cómo frenan bajando el cuerpo y apoyando bien el pie exterior. Luego monta tu «T de agilidad» casera con 4 botellas.",
        pasos: [
          "Coloca 4 botellas formando una T (3 m entre ellas si tienes espacio; adapta la distancia a tu zona).",
          "Recorre la T: carrera al frente, lateral a la derecha, lateral a la izquierda, carrera de espaldas al inicio.",
          "Cronometra 5 intentos con descanso entre ellos. Apunta tu mejor tiempo.",
          "Varía: hazlo tocando cada botella, o con una pelota en las manos.",
        ],
        entrega: "Tus 5 tiempos en la T de agilidad y una frase: ¿qué truco del vídeo te ayudó más?",
      },
      {
        id: "a4", titulo: "Circuito de desplazamientos por superficies", fase: "aplicacion", duracion: "45 min",
        inteligencias: ["corp", "espa", "natu"],
        video: "hTWKbfoikeg",
        desc: "Diseña y ejecuta un circuito que combine desplazamientos en diferentes superficies (baldosa, alfombra, colchoneta, césped o arena si puedes salir al parque o la playa 🏖️). Cada superficie cambia tu equilibrio: ¡siéntelo y adáptate!",
        pasos: [
          "Elige al menos 3 superficies diferentes y 4 tipos de desplazamiento (lateral, pata coja, cuadrupedia, carrera con cambios de ritmo).",
          "Dibuja el mapa del circuito indicando superficie y desplazamiento en cada tramo.",
          "Realiza el circuito 3 veces. Anota en cuál superficie te costó más equilibrarte y por qué crees que pasa.",
          "Si sales al exterior: ve acompañado/a de un adulto y aplica tu checklist de seguridad.",
        ],
        entrega: "Mapa del circuito + respuesta razonada sobre la superficie más difícil.",
      },
      {
        id: "a5", titulo: "Test interactivo: cerebro en juego", fase: "aplicacion", duracion: "25 min",
        inteligencias: ["logi", "ling"],
        video: "YQHsXMglC9A",
        desc: "Demuestra lo que sabes en un test interactivo gamificado (enlace en Classroom) sobre seguridad, calentamiento, equilibrio y agilidad. Pero antes, repasa con el vídeo. Objetivo: ¡superar el 80% de aciertos!",
        pasos: [
          "Repasa el vídeo-resumen de la unidad.",
          "Haz el test interactivo desde el enlace de Classroom (puedes intentarlo 2 veces).",
          "Apunta las preguntas que fallaste y busca la respuesta correcta.",
          "Inventa TÚ una pregunta nueva de tipo test (con 4 opciones y una correcta) para el banco de preguntas de la clase.",
        ],
        entrega: "Captura de tu resultado del test + tu pregunta inventada con sus 4 opciones.",
      },
      {
        id: "a6", titulo: "Videomontaje: la experiencia de los retos", fase: "integracion", duracion: "60 min",
        inteligencias: ["espa", "intra", "ling"],
        video: "RgKAFK5djSk",
        desc: "Repite las 5 pruebas de 60 segundos de la primera actividad y compara con tus marcas iniciales. Después monta tu vídeo-resumen «Antes y después»: la prueba científica de tu superación.",
        pasos: [
          "Repite las 5 pruebas de 60 s y anota los nuevos resultados junto a los antiguos.",
          "Calcula tu mejora en cada prueba (resta: ahora − antes). ¿Acertaste tu predicción?",
          "Monta el videomontaje (máx. 2 min): clips del antes, del entrenamiento y del después, con rótulos de tus marcas.",
          "Termina el vídeo con tu «frase de campeón/a»: un consejo para quien empiece estos retos.",
        ],
        entrega: "Videomontaje final + tabla comparativa antes/después.",
      },
    ],
  },

  /* ============ UP 4 ============ */
  {
    id: "up4",
    num: 4,
    titulo: "Golpe maestro",
    emoji: "🏓",
    tagline: "Golpeos, precisión y coordinación óculo-manual con material casero.",
    trimestre: 2,
    fechas: "8 enero – 29 enero",
    sesiones: 10,
    color: "#f59e0b",
    color2: "#ef4444",
    reto: "🌟 Reto de la unidad: fabrica tu propia pala, entrena tus golpeos y organiza un mini torneo familiar con acta de resultados y premio al juego limpio.",
    justificacion: "Propuesta lúdica para desarrollar habilidades de golpeo, coordinación óculo-manual, precisión y control del móvil en movimiento, mejorando la capacidad de anticipación y el ajuste del movimiento.",
    criterios: ["1.1 Explorar las posibilidades de la motricidad a través del juego, con hábitos de higiene, postura, descanso e hidratación.", "3.1 Intervenir en situaciones motrices lúdicas con esfuerzo, deportividad y autorregulación, respetando normas y reglas."],
    saberes: ["Toma de decisiones en juegos y deportes en situaciones motrices individuales.", "Prevención de lesiones: activación y vuelta a la calma.", "Aplicación del juego limpio."],
    productos: ["Circuito de habilidad", "Estaciones de máximas", "Test normativo", "Torneo"],
    actividades: [
      {
        id: "a1", titulo: "¿Qué puedo golpear? Inventario del deportista", fase: "activacion", duracion: "30 min",
        inteligencias: ["logi", "natu", "espa"],
        video: "XqZsoesa55w",
        desc: "Los deportes de raqueta empiezan por el material. Verás un vídeo sobre deportes de golpeo (bádminton, palas, tenis de mesa…) y después harás un inventario de móviles y «raquetas» que puedes crear en casa reutilizando materiales. ♻️",
        pasos: [
          "Ve el vídeo y apunta los 3 deportes de golpeo que más te gusten.",
          "Busca por casa móviles seguros: globo, pelota de calcetines, pompón, tapón, pelota de papel con cinta…",
          "Fabrica tu pala reciclada: cartón duro + palo o percha forrada + cinta adhesiva. ¡Decórala a tu estilo!",
          "Prueba cada móvil con tu pala: ¿cuál bota más?, ¿cuál flota?, ¿cuál es más difícil de controlar? Ordénalos de fácil a difícil.",
        ],
        entrega: "Foto de tu pala fabricada y tu ranking de móviles de fácil a difícil.",
      },
      {
        id: "a2", titulo: "La técnica del golpeo", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "espa"],
        video: "JGwWNGJdvx8",
        desc: "Un golpe maestro tiene 3 secretos: mirar el móvil, preparar el brazo atrás y acompañar el golpe hacia donde quieres que vaya. Obsérvalos en el vídeo a cámara lenta y practica el gesto en vacío antes de golpear de verdad.",
        pasos: [
          "Observa el vídeo: posición de pies (uno adelantado), preparación y acompañamiento.",
          "Práctica en vacío: 10 golpes de derecha y 10 de revés SIN móvil, exagerando el gesto.",
          "Con globo: golpea hacia arriba y deja que baje. 20 con la derecha, 20 con el revés.",
          "Reto: alterna derecha-revés sin que el globo toque el suelo. ¿Cuál es tu récord?",
        ],
        entrega: "Vídeo (30 s) de tu serie alternando derecha y revés + tu récord de toques.",
      },
      {
        id: "a3", titulo: "Control total: el móvil te obedece", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "intra"],
        video: "L_jWHffIx5E",
        desc: "Antes de golpear fuerte hay que golpear FINO. En el vídeo verás ejercicios de control: toques suaves, golpeos a diferentes alturas y cambios de mano. La pala debe ser una prolongación de tu brazo.",
        pasos: [
          "Toques de control con la pala hacia arriba: series de 10, 20 y 30 sin que caiga el móvil.",
          "Toques bajitos (a la altura de tu cintura) y toques altos (por encima de tu cabeza), 10 de cada.",
          "Cambio de mano: 5 toques con tu mano buena, 5 con la otra. ¡Entrena los dos lados!",
          "Camina mientras das toques: de una pared a otra de la habitación sin perder el control.",
        ],
        entrega: "Tabla con tus récords de cada ejercicio de control.",
      },
      {
        id: "a4", titulo: "Estaciones de máximas", fase: "aplicacion", duracion: "40 min",
        inteligencias: ["corp", "logi"],
        video: "9bZkp7q19f0",
        desc: "Monta 4 estaciones en tu zona de entrenamiento y busca tu MÁXIMA puntuación en cada una. Registra los datos como un analista deportivo: la estadística también es Educación Física.",
        pasos: [
          "Estación 1: toques seguidos con la pala sin que caiga el móvil (récord de toques).",
          "Estación 2: golpea el globo contra la pared y vuelve a golpearlo (récord de rebotes).",
          "Estación 3: puntería: golpea el móvil hacia un cubo o caja a 2-3 pasos (aciertos de 10 intentos).",
          "Estación 4: peloteo cooperativo con alguien de casa (récord de golpeos entre los dos).",
          "Haz 3 rondas completas y construye tu tabla de máximas.",
        ],
        entrega: "Tabla de máximas de las 4 estaciones (3 rondas) + tu mejor marca destacada.",
      },
      {
        id: "a5", titulo: "Test normativo: las reglas del juego", fase: "aplicacion", duracion: "25 min",
        inteligencias: ["ling", "logi"],
        video: "YQHsXMglC9A",
        desc: "Todo torneo necesita reglas claras. Aprenderás las normas básicas de los juegos de golpeo (saque, punto, falta, cambio de campo) y redactarás el reglamento oficial de tu propio torneo familiar.",
        pasos: [
          "Ve el vídeo sobre las reglas básicas de los deportes de raqueta.",
          "Haz el test normativo de Classroom (¿cuándo es punto?, ¿cuándo es falta?…).",
          "Redacta el reglamento de tu torneo: 5 reglas + 1 regla de juego limpio inventada por ti.",
          "Decide el sistema de puntuación (por ejemplo: sets a 7 puntos).",
        ],
        entrega: "Captura del test + tu reglamento con las 6 reglas.",
      },
      {
        id: "a6", titulo: "Mini torneo familiar «Golpe Maestro»", fase: "integracion", duracion: "60 min + torneo",
        inteligencias: ["inter", "logi", "corp"],
        video: "pRpeEdMmmQ0",
        desc: "¡Llegó el gran día! Organiza el torneo con tu reglamento, tus palas y tus estaciones. Tú eres jugador/a, árbitro y organizador/a. Al final, entrega el premio más importante: el del juego limpio.",
        pasos: [
          "Prepara el espacio, el material y el acta de resultados (cuadro con los nombres y puntuaciones).",
          "Explica las reglas a tu familia antes de empezar (como un buen árbitro).",
          "Juega el torneo completo y registra los resultados en el acta.",
          "Ceremonia final: entrega el «Premio al Juego Limpio» a quien mejor haya respetado las reglas y a los demás, y explica por qué.",
        ],
        entrega: "Foto del acta de resultados + foto de la entrega del premio + 3 líneas: ¿qué fue lo mejor del torneo?",
      },
    ],
  },

  /* ============ UP 5 ============ */
  {
    id: "up5",
    num: 5,
    titulo: "¡Atrapa, lanza y… disfruta!",
    emoji: "🎯",
    tagline: "Lanzamientos, recepciones y puntería en tiempo real.",
    trimestre: 2,
    fechas: "2 febrero – 2 marzo",
    sesiones: 10,
    color: "#ef4444",
    color2: "#f97316",
    reto: "🌟 Reto de la unidad: completa el «Calendario de 10 retos de puntería» y corona tu entrenamiento con un torneo de dianas y un videomontaje de tus mejores lanzamientos.",
    justificacion: "Propuesta dinámica que introduce las actividades de lanzamiento y recepción: golpeo, pase, coordinación óculo-manual y control del desplazamiento, fomentando la anticipación, la toma de decisiones en tiempo real y la cooperación.",
    criterios: ["1.1 Explorar las posibilidades de la motricidad a través del juego con hábitos saludables.", "3.2 Mostrar habilidades sociales, diálogo y respeto en la resolución de conflictos y ante la diversidad."],
    saberes: ["Toma de decisiones en juegos y deportes en situaciones motrices individuales.", "Estrategias de trabajo en equipo para la resolución constructiva de conflictos."],
    productos: ["Circuito de control", "Retos diarios", "Test normativo", "Torneo", "Videomontaje"],
    actividades: [
      {
        id: "a1", titulo: "Lluvia de lanzamientos", fase: "activacion", duracion: "25 min",
        inteligencias: ["corp", "logi"],
        video: "OPf0YbXqDm0",
        desc: "¿De cuántas formas se puede lanzar un objeto? Por abajo, por arriba, de pecho, de espaldas, entre las piernas… Explora TODAS las formas posibles con tu pelota de calcetines y clasifícalas: descubrirás que ya sabes más de lo que crees.",
        pasos: [
          "Ve el vídeo con distintos tipos de lanzamiento en varios deportes.",
          "Con tu pelota de calcetines, inventa y prueba al menos 8 formas diferentes de lanzar.",
          "Clasifícalas en una tabla: precisas / potentes / creativas.",
          "Elige tu lanzamiento estrella y ponle nombre (ej.: «el cohete lateral»).",
        ],
        entrega: "Tu tabla de 8 lanzamientos clasificados + vídeo (15 s) de tu lanzamiento estrella.",
      },
      {
        id: "a2", titulo: "Lanzar y recibir como un pro", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "espa"],
        video: "pRpeEdMmmQ0",
        desc: "La técnica del pase y la recepción: pies orientados, mirada al objetivo, brazos que amortiguan «abrazando» el balón. Míralo en el vídeo y entrena contra la pared: la pared es la compañera que nunca falla.",
        pasos: [
          "Observa en el vídeo cómo se orientan los pies y cómo las manos reciben en forma de triángulo.",
          "Pared: 20 pases de pecho, 20 por encima de la cabeza, 20 con bote.",
          "Aléjate un paso cada 5 recepciones sin fallo. ¿A qué distancia llegas?",
          "Recepciones sorpresa: lanza, gira sobre ti mismo/a y recibe. 10 intentos.",
        ],
        entrega: "Tus marcas: distancia máxima a la pared y aciertos en las recepciones sorpresa.",
      },
      {
        id: "a3", titulo: "Puntería fina: fábrica de dianas", fase: "demostracion", duracion: "35 min",
        inteligencias: ["espa", "corp", "logi"],
        video: "CevxZvSJLk8",
        desc: "La puntería se entrena con dianas de distintos tamaños y distancias. Verás cómo construir 3 tipos de diana con material reciclado (cubo, aro de papel en la pared, botellas-bolos) y las probarás con puntuaciones.",
        pasos: [
          "Fabrica 3 dianas: horizontal (cubo o caja), vertical (círculo de papel en la pared) y derribable (botellas de plástico).",
          "Asigna puntos a cada diana según dificultad (ej.: cubo 1 pt, círculo 2 pts, botella central 3 pts).",
          "Serie de prueba: 10 lanzamientos a cada diana desde 3 pasos. Anota tus puntos.",
          "Descubre tu distancia ideal: prueba desde 2, 4 y 6 pasos. ¿Dónde aciertas más?",
        ],
        entrega: "Foto de tus 3 dianas + tabla de puntuaciones por distancia.",
      },
      {
        id: "a4", titulo: "Circuito de control", fase: "aplicacion", duracion: "40 min",
        inteligencias: ["corp", "logi"],
        video: "9bZkp7q19f0",
        desc: "Combina todo: desplazamiento + lanzamiento + recepción en un circuito de 4 postas que tú mismo/a diseñas. El objetivo es mantener el CONTROL del móvil aunque tu cuerpo esté en movimiento: así funcionan los deportes de verdad.",
        pasos: [
          "Posta 1: desplázate lateralmente botando o lanzando y recibiendo tu pelota.",
          "Posta 2: lanza a tu diana favorita, recoge y sprinta a la siguiente posta.",
          "Posta 3: lanza al aire, da una vuelta completa y recibe.",
          "Posta 4: pases contra la pared en movimiento (caminando en paralelo a ella).",
          "Cronometra el circuito completo con un límite: cada fallo suma 3 segundos. Haz 3 intentos.",
        ],
        entrega: "Esquema del circuito + tus 3 tiempos con las penalizaciones.",
      },
      {
        id: "a5", titulo: "Retos diarios: calendario de puntería", fase: "aplicacion", duracion: "15 min al día × 10 días",
        inteligencias: ["intra", "corp"],
        video: "7wtfhZwyrcc",
        desc: "Un calendario de 10 días con un mini reto diario de lanzamiento o recepción. La constancia es el súper-poder de los deportistas: 15 minutos al día valen más que 3 horas un solo día.",
        pasos: [
          "Descarga el calendario de retos de Classroom (o cópialo en una cartulina).",
          "Cada día completa el reto y colorea la casilla: conseguido ✔ / casi 🔁 / mañana lo repito ↩.",
          "Retos ejemplo: 5 canastas seguidas al cubo, recibir 10 veces sin fallo con la mano no dominante, derribar 3 botellas en 5 tiros…",
          "Día 10: repite el reto del día 1. ¿Notas la diferencia?",
        ],
        entrega: "Foto de tu calendario completado con los 10 días coloreados.",
      },
      {
        id: "a6", titulo: "Torneo de dianas + videomontaje", fase: "integracion", duracion: "60 min",
        inteligencias: ["inter", "espa", "ling"],
        video: "RgKAFK5djSk",
        desc: "Cierre por todo lo alto: organiza un torneo de puntería con tu familia usando tus dianas y tu sistema de puntos. Grábalo y monta un videomontaje con los mejores lanzamientos… ¡y también con los fallos más divertidos, que de ellos se aprende!",
        pasos: [
          "Prepara las dianas, el orden de tiro y la hoja de puntuaciones.",
          "Antes de empezar, pacta con los participantes una «regla de oro del respeto» (ej.: animamos siempre, nunca nos reímos DE alguien, solo CON alguien).",
          "Celebra el torneo (mínimo 2 rondas por persona) y registra los puntos.",
          "Monta tu videomontaje (máx. 2 min): mejores lanzamientos + tomas falsas + podio final.",
        ],
        entrega: "Videomontaje del torneo + hoja de puntuaciones.",
      },
    ],
  },

  /* ============ UP 6 ============ */
  {
    id: "up6",
    num: 6,
    titulo: "Pequeños grandes jugadores en acción",
    emoji: "⚽",
    tagline: "Juegos con pelota, cooperación y deportes alternativos e inclusivos.",
    trimestre: 2,
    fechas: "4 marzo – 26 marzo",
    sesiones: 11,
    color: "#22c55e",
    color2: "#0d9488",
    reto: "🌟 Reto de la unidad: inventa un deporte alternativo 100% inclusivo, escribe sus reglas y estrénalo en un «Evento Alternativo» con tu familia.",
    justificacion: "Desarrollo de habilidades motrices básicas mediante juegos con pelota y móviles, mejorando coordinación, control corporal e interacción. El grupo resuelve problemas motores, toma decisiones y coopera, con mirada crítica hacia el sexismo en el deporte.",
    criterios: ["1.1 Utilizar la actividad física como alternativa de ocio saludable y sostenible.", "2.2 Adquirir un progresivo control y dominio corporal implementando retos motores individuales o grupales."],
    saberes: ["Identificación y abordaje del sexismo en el deporte amateur y profesional.", "Ajuste espacio-temporal en situaciones cooperativas y de interacción con móviles."],
    productos: ["Circuito de control", "Retos diarios", "Test normativo", "Evento alternativo", "Videomontaje"],
    actividades: [
      {
        id: "a1", titulo: "¿Deporte de chicos o de chicas? ¡De personas!", fase: "activacion", duracion: "30 min",
        inteligencias: ["ling", "inter", "intra"],
        video: "pRpeEdMmmQ0",
        desc: "¿Existen deportes «de chicos» y deportes «de chicas»? Verás un vídeo sobre deportistas que rompieron estereotipos y harás una mini investigación en casa. Espóiler: el deporte no tiene género, tiene pasión.",
        pasos: [
          "Ve el vídeo y anota qué deportistas aparecen y qué barreras superaron.",
          "Mini encuesta en casa: pregunta a 2-3 personas si de pequeños había deportes «prohibidos» para chicos o chicas.",
          "Busca (con ayuda de un adulto) una deportista canaria y un deportista canario actuales y apunta un logro de cada uno.",
          "Escribe tu conclusión en 3 líneas: ¿qué le dirías a alguien que dice que un deporte «no es para ti»?",
        ],
        entrega: "Resultados de tu encuesta + tus dos deportistas canarios + tu conclusión.",
      },
      {
        id: "a2", titulo: "Deportes alternativos: colpbol, kin-ball y más", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "inter"],
        video: "9bZkp7q19f0",
        desc: "¿Conoces el colpbol, el kin-ball, el tchoukball o el bucketball? Son deportes alternativos creados para que TODOS jueguen y nadie se quede fuera. En el vídeo verás sus reglas más curiosas: fíjate en qué los hace tan inclusivos.",
        pasos: [
          "Ve el vídeo y apunta el nombre de 3 deportes alternativos y una regla curiosa de cada uno.",
          "Analiza como un experto: ¿qué hace inclusivo a cada deporte? (ej.: en colpbol nadie puede tocar el balón dos veces seguidas: ¡obligatorio cooperar!).",
          "Practica el gesto base del colpbol: golpear el globo/pelota con las manos juntas, 20 toques.",
          "Elige el deporte alternativo que más te gustaría probar en clase y justifica por qué.",
        ],
        entrega: "Tu ficha de los 3 deportes con su regla curiosa y tu elección justificada.",
      },
      {
        id: "a3", titulo: "Pases y desmarque: piensa antes de recibir", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "espa", "logi"],
        video: "JGwWNGJdvx8",
        desc: "En los juegos de equipo, moverse SIN balón es tan importante como tenerlo. El desmarque es escaparse de tu defensor para ofrecer un pase seguro. Míralo en el vídeo y entrénalo con un juego de sombras en casa.",
        pasos: [
          "Observa en el vídeo cómo el jugador se aleja y aparece en un espacio libre (¡y siempre mirando el balón!).",
          "Juego de la sombra: una persona de tu casa te sigue (defensor); tú intentas «perderla» con cambios de ritmo y dirección en 10 segundos.",
          "Con pelota: pídele que te pase solo cuando estés desmarcado/a. 10 recepciones válidas.",
          "Piensa y responde: ¿por qué es mejor pasar al espacio que al pie del compañero que está tapado?",
        ],
        entrega: "Vídeo corto del juego de la sombra + tu respuesta a la pregunta táctica.",
      },
      {
        id: "a4", titulo: "Inventa tu deporte alternativo", fase: "aplicacion", duracion: "50 min",
        inteligencias: ["logi", "ling", "inter", "espa"],
        video: "L_jWHffIx5E",
        desc: "La actividad más creativa del curso: diseña TU propio deporte alternativo e inclusivo. Tendrá nombre, material casero, terreno de juego, sistema de puntuación y —lo más importante— reglas que garanticen que todo el mundo participa.",
        pasos: [
          "Elige el material (globo, pelota de calcetines, cubos…) y dibuja el terreno de juego.",
          "Escribe las 6 reglas de tu deporte. Al menos 2 deben ser de inclusión (ej.: «punto doble si han tocado el balón todos los jugadores», «no se puede tocar dos veces seguidas»).",
          "Ponle un nombre original y diseña su logo.",
          "Haz una prueba piloto tú solo/a o con alguien de casa y ajusta lo que no funcione (¡así trabajan los diseñadores de juegos!).",
        ],
        entrega: "Ficha completa de tu deporte: nombre, logo, dibujo del campo, material y las 6 reglas.",
      },
      {
        id: "a5", titulo: "Circuito de control con móviles", fase: "aplicacion", duracion: "35 min",
        inteligencias: ["corp", "logi"],
        video: "ktvTqknDobU",
        desc: "Entrenamiento tipo «jugador total»: un circuito de 4 postas con conducción, pase, recepción y lanzamiento, mezclando mano y pie. La coordinación óculo-manual y óculo-pédica se entrenan juntas.",
        pasos: [
          "Posta 1: conduce la pelota con el pie entre 4 obstáculos (slalom), ida y vuelta.",
          "Posta 2: 10 pases contra la pared con la mano y 10 con el pie.",
          "Posta 3: lanza al cubo-diana desde 3 pasos, 5 intentos.",
          "Posta 4: 15 toques de globo alternando mano-pie-cabeza.",
          "Registra tus resultados de 2 vueltas completas al circuito.",
        ],
        entrega: "Tabla de resultados de las 2 vueltas al circuito.",
      },
      {
        id: "a6", titulo: "El Evento Alternativo", fase: "integracion", duracion: "60 min + evento",
        inteligencias: ["inter", "corp", "ling"],
        video: "OPf0YbXqDm0",
        desc: "¡Estreno mundial! Presenta tu deporte inventado a tu familia y celebrad el primer partido oficial de la historia. Grábalo, evalúa qué reglas funcionaron y cuáles cambiarías: los mejores juegos se pulen jugando.",
        pasos: [
          "Explica tu deporte a los participantes con tu ficha (nombre, reglas, puntuación).",
          "Jugad el primer partido oficial (10-15 minutos).",
          "Después del partido, pregunta a los jugadores: ¿qué regla os gustó más? ¿Cambiaríais algo?",
          "Escribe la versión 2.0 de una de tus reglas a partir del feedback recibido.",
        ],
        entrega: "Vídeo o fotos del evento + tu regla mejorada 2.0 y por qué la cambiaste.",
      },
    ],
  },

  /* ============ UP 7 ============ */
  {
    id: "up7",
    num: 7,
    titulo: "Raíces en movimiento",
    emoji: "🌋",
    tagline: "Juegos y deportes tradicionales de Canarias: nuestro patrimonio en juego.",
    trimestre: 3,
    fechas: "6 abril – 29 abril",
    sesiones: 11,
    color: "#0d9488",
    color2: "#ca8a04",
    reto: "🌟 Reto de la unidad: rescata un juego tradicional canario, fabrica su material con elementos reciclados y enséñaselo a tu familia como hacían nuestros abuelos y abuelas.",
    justificacion: "Conocimiento y práctica de juegos y deportes tradicionales de Canarias para acercar al alumnado al patrimonio cultural de su entorno a través de la actividad física, fomentando el respeto, la convivencia y el conocimiento de nuestras tradiciones.",
    criterios: ["1.2 Aplicar medidas de seguridad antes, durante y después de la práctica.", "4.1 Practicar juegos motores y deportes propios de la cultura canaria, conservando y transmitiendo su valor cultural."],
    saberes: ["Valoración y transmisión de la cultura motriz canaria: juegos, deportes y danzas como seña de identidad.", "Reconocimiento del esfuerzo en el deporte, evitando estereotipos.", "Deportes asociados a grandes eventos locales, nacionales e internacionales."],
    productos: ["Demostraciones prácticas", "Test de reglamento", "Torneo", "Mural explicativo"],
    actividades: [
      {
        id: "a1", titulo: "¿A qué jugaban nuestros abuelos y abuelas?", fase: "activacion", duracion: "35 min",
        inteligencias: ["ling", "inter"],
        video: "fJ9rUzIMcZQ",
        desc: "Los juegos tradicionales viajan de generación en generación… ¡pero solo si alguien los transmite! Hoy serás periodista: entrevistarás a una persona mayor de tu familia o vecindario sobre los juegos de su infancia en Canarias.",
        pasos: [
          "Ve el vídeo introductorio sobre juegos tradicionales.",
          "Prepara tu entrevista con 5 preguntas (¿a qué jugabas?, ¿con qué material?, ¿dónde?, ¿quién te enseñó?, ¿me lo enseñas?).",
          "Haz la entrevista (presencial, por teléfono o videollamada) y toma notas o grábala con permiso.",
          "Elige el juego que más te sorprendió y descríbelo con tus palabras.",
        ],
        entrega: "Tus 5 preguntas con sus respuestas + la descripción del juego que más te gustó.",
      },
      {
        id: "a2", titulo: "Tesoros del patrimonio: billarda, pina y bola canaria", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "natu"],
        video: "kJQP7kiw5Fk",
        desc: "Descubre tres joyas del juego tradicional canario: la billarda, la pina y la bola canaria. En el vídeo verás cómo se juegan, con qué material y en qué islas son más populares. Presta atención: luego construirás tu versión casera.",
        pasos: [
          "Ve el vídeo y completa la ficha de cada juego: material, número de jugadores y objetivo.",
          "Apunta una curiosidad de cada juego (ej.: en qué isla se juega más).",
          "Practica el gesto de la bola canaria: lanzamiento por abajo, suave y rasante, con una pelota hacia una zapatilla-boliche.",
          "Pregunta en casa si alguien ha jugado alguna vez a alguno de los tres.",
        ],
        entrega: "Ficha de los 3 juegos completada + tu récord de acercamiento al «boliche» casero (5 lanzamientos).",
      },
      {
        id: "a3", titulo: "El salto del pastor y otras destrezas", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "espa", "natu"],
        video: "hTWKbfoikeg",
        desc: "El salto del pastor canario nació de la necesidad de moverse por barrancos con una lanza (garrote). Hoy es deporte tradicional. Verás la técnica en el vídeo y entrenarás EN VERSIÓN SEGURA sus fundamentos: equilibrio, apoyo y recepción.",
        pasos: [
          "Ve el vídeo fijándote en cómo colocan las manos en el garrote y cómo reciben con las piernas flexionadas.",
          "SIN garrote (seguridad primero): practica la recepción del salto: salta desde el suelo y aterriza silenciosamente con rodillas dobladas, 10 veces.",
          "Con un palo de escoba APOYADO EN EL SUELO (nunca saltando con él): practica el equilibrio del pastor: sujeta el palo vertical y camina alrededor cambiando de manos.",
          "Investiga: ¿en qué islas se practica más el salto del pastor? ¿Cómo se llama el bastón?",
        ],
        entrega: "Vídeo de tus recepciones silenciosas + respuestas de tu mini investigación.",
      },
      {
        id: "a4", titulo: "Fabrica tu juego tradicional reciclado", fase: "aplicacion", duracion: "50 min",
        inteligencias: ["espa", "natu", "corp"],
        video: "XqZsoesa55w",
        desc: "Como antes no había tiendas de deporte, ¡el material se fabricaba en casa! Construirás el material de un juego tradicional canario con elementos reciclados: consumo responsable y patrimonio, todo en uno. ♻️",
        pasos: [
          "Elige tu juego: bola canaria (pelotas + boliche), billarda (dos palos), tángana/chapas (chapas decoradas) o el juego de tu entrevista.",
          "Reúne material reciclado: papel de periódico y cinta para bolas, cartón, tapones, chapas…",
          "Fabrica el material y decóralo con motivos canarios (¡puntos extra por creatividad!).",
          "Prueba tu juego y ajusta el material si hace falta (¿la bola rueda bien?, ¿pesa demasiado poco?).",
        ],
        entrega: "Foto de tu material fabricado + vídeo (30 s) jugando con él.",
      },
      {
        id: "a5", titulo: "Test de reglamento: sabios de la tradición", fase: "aplicacion", duracion: "25 min",
        inteligencias: ["ling", "logi"],
        video: "YQHsXMglC9A",
        desc: "Demuestra cuánto sabes ya del patrimonio lúdico canario con el test de reglamento (enlace en Classroom): reglas, materiales, islas y nombres propios de nuestros juegos y deportes tradicionales.",
        pasos: [
          "Repasa tus fichas de las actividades anteriores y el vídeo-resumen.",
          "Completa el test de reglamento en Classroom (2 intentos).",
          "Corrige tus fallos buscando la respuesta correcta.",
          "Propón una pregunta nueva para el test del año que viene, sobre el juego de tu entrevista.",
        ],
        entrega: "Captura de tu resultado + tu pregunta propuesta con su respuesta.",
      },
      {
        id: "a6", titulo: "Mural explicativo: Raíces en movimiento", fase: "integracion", duracion: "60 min",
        inteligencias: ["espa", "ling", "inter"],
        video: "RgKAFK5djSk",
        desc: "Gran cierre: crea tu aportación al mural colaborativo «Raíces en movimiento» de la clase. Tu misión como guardián/a del patrimonio: que el juego que rescataste no se pierda nunca. Enséñaselo también a tu familia.",
        pasos: [
          "Diseña tu tarjeta para el mural: nombre del juego, isla de origen, material, reglas en 4 pasos y un dibujo o foto.",
          "Añade la frase de la persona entrevistada que más te gustó (con su permiso).",
          "Publica tu tarjeta en el mural digital de la clase (enlace en Classroom).",
          "Enseña el juego a alguien de tu casa que no lo conociera: ¡acabas de transmitir patrimonio! 🏆",
        ],
        entrega: "Tu tarjeta publicada en el mural + foto enseñando el juego a tu familia.",
      },
    ],
  },

  /* ============ UP 8 ============ */
  {
    id: "up8",
    num: 8,
    titulo: "Guanches al terrero",
    emoji: "🥋",
    tagline: "Lucha canaria, juego del palo y deportes autóctonos: la herencia guanche.",
    trimestre: 3,
    fechas: "30 abril – 21 mayo",
    sesiones: 10,
    color: "#ca8a04",
    color2: "#b45309",
    reto: "🌟 Reto de la unidad: conviértete en cronista deportivo del pasado: domina las mañas básicas (versión segura), supera el test de reglamento y construye un mural histórico de los deportes guanches.",
    justificacion: "Conocimiento y práctica de actividades físicas vinculadas a los deportes autóctonos canarios para fomentar un estilo de vida activo y saludable y la valoración del entorno sociocultural, desarrollando respeto, convivencia, cooperación, inclusión y juego limpio.",
    criterios: ["1.2 Aplicar medidas de seguridad antes, durante y después de la práctica.", "4.1 Practicar juegos motores y deportes propios de la cultura canaria, transmitiendo su valor cultural."],
    saberes: ["Reconocimiento del esfuerzo en el deporte y aceptación de las diferentes tipologías corporales.", "Deportes asociados a grandes eventos locales, nacionales e internacionales: la lucha canaria."],
    productos: ["Demostraciones prácticas", "Test de reglamento", "Jornada deportiva", "Mural histórico"],
    actividades: [
      {
        id: "a1", titulo: "¿Quiénes eran los guanches?", fase: "activacion", duracion: "30 min",
        inteligencias: ["ling", "logi"],
        video: "fJ9rUzIMcZQ",
        desc: "Viaje en el tiempo: los antiguos habitantes de Canarias ya competían en lucha, salto y lanzamiento mucho antes de que existieran los gimnasios. Verás un vídeo sobre su historia y conectarás pasado y presente del deporte canario.",
        pasos: [
          "Ve el vídeo sobre los aborígenes canarios y sus prácticas físicas.",
          "Completa la línea del tiempo: ¿qué deportes actuales heredamos de ellos? (lucha canaria, salto del pastor, juego del palo, levantamiento de piedra…).",
          "Responde: ¿por qué crees que la lucha era importante en su sociedad?",
          "Comparte en casa un dato que hayas aprendido y anota la reacción.",
        ],
        entrega: "Tu línea del tiempo + tus respuestas.",
      },
      {
        id: "a2", titulo: "La lucha canaria: el noble arte del terrero", fase: "demostracion", duracion: "35 min",
        inteligencias: ["corp", "inter"],
        video: "9bZkp7q19f0",
        desc: "La lucha canaria es único en el mundo: gana quien derriba, pero se ayuda al rival a levantarse. En el vídeo conocerás el terrero, la vestimenta, la «agarrada» y las mañas más famosas. Fíjate sobre todo en los valores: nobleza y respeto.",
        pasos: [
          "Ve el vídeo y apunta: qué es el terrero, cómo se agarra y 3 nombres de mañas (ej.: burra, cogida de muslo, toque para atrás).",
          "Copia el «código del luchador»: se saluda antes y después, se ayuda al rival a levantarse, no hay golpes.",
          "SIN CONTACTO (versión segura en casa): practica la posición base del luchador: piernas flexionadas, espalda recta, pasos laterales sin cruzar los pies, 3 series de 30 segundos.",
          "Practica la «lucha de equilibrios» con un cojín grande: empuja el cojín contra la pared manteniendo la posición base.",
        ],
        entrega: "Tus notas del vídeo + vídeo (20 s) de tu posición base con desplazamientos.",
      },
      {
        id: "a3", titulo: "Juego del palo y levantamiento de piedra", fase: "demostracion", duracion: "30 min",
        inteligencias: ["corp", "espa"],
        video: "hTWKbfoikeg",
        desc: "Dos deportes autóctonos más: el juego del palo canario (esgrima con vara, pura coordinación) y el levantamiento y pulseo de piedra (fuerza y técnica). Los verás en el vídeo y entrenarás sus fundamentos con versión adaptada y segura.",
        pasos: [
          "Observa en el vídeo la posición y los movimientos del juego del palo: la vara nunca busca golpear, es un arte de floreo y control.",
          "Con un palo de escoba y MUCHO espacio libre: practica los giros de muñeca y los cambios de mano A CÁMARA LENTA, lejos de personas y objetos.",
          "Versión segura del levantamiento: técnica de levantar peso con las piernas (no con la espalda) usando una mochila con libros: 10 repeticiones perfectas.",
          "Responde: ¿por qué la técnica importa más que la fuerza al levantar peso?",
        ],
        entrega: "Vídeo de tu técnica de levantamiento con mochila + tu respuesta razonada.",
      },
      {
        id: "a4", titulo: "Entrenamiento del pequeño luchador", fase: "aplicacion", duracion: "40 min",
        inteligencias: ["corp", "intra"],
        video: "7wtfhZwyrcc",
        desc: "Los luchadores entrenan equilibrio, fuerza de piernas y agarre. Diseña tu sesión de entrenamiento «guanche» con 5 ejercicios adaptados a casa, cronometrados y con registro de sensaciones. ¡Entrena como en el terrero!",
        pasos: [
          "Ejercicio 1: posición base del luchador con desplazamientos, 3×30 s.",
          "Ejercicio 2: «lucha del cojín» contra la pared, 3×20 s.",
          "Ejercicio 3: sentadillas guanches (lentas y profundas), 3×10.",
          "Ejercicio 4: equilibrio a pata coja con empujones suaves de un familiar (¡sin derribar!), 3×20 s por pierna.",
          "Ejercicio 5: agarre: cuelga una toalla de una barra o puerta y tira de ella (isométrico), 3×15 s. Termina con tu vuelta a la calma.",
        ],
        entrega: "Tu ficha de entrenamiento completada con series, tiempos y cómo te sentiste (1-5 ⭐).",
      },
      {
        id: "a5", titulo: "Test de reglamento + demostración práctica", fase: "aplicacion", duracion: "30 min",
        inteligencias: ["ling", "logi", "corp"],
        video: "YQHsXMglC9A",
        desc: "Doble prueba de cronista deportivo: el test de reglamento de la lucha canaria (puntuación, la «agarrada», qué es «dar una») y una demostración práctica grabada de la posición base y una maña explicada con tus palabras.",
        pasos: [
          "Repasa tus notas y el vídeo de la actividad 2.",
          "Haz el test de reglamento en Classroom.",
          "Graba tu demostración: posición base + explica UNA maña con tus palabras (puedes usar peluches para la demo… ¡sin contacto real!).",
          "Termina el vídeo nombrando los 2 valores de la lucha canaria que más te gustan.",
        ],
        entrega: "Captura del test + tu vídeo-demostración (máx. 1 min).",
      },
      {
        id: "a6", titulo: "Mural histórico: Guanches al terrero", fase: "integracion", duracion: "60 min",
        inteligencias: ["espa", "ling", "inter"],
        video: "RgKAFK5djSk",
        desc: "Cierre de unidad: construye tu aportación al mural histórico colaborativo. Una línea del tiempo del deporte canario, de los guanches a los campeones actuales, para que toda la comunidad educativa la disfrute en la jornada deportiva.",
        pasos: [
          "Elige tu casilla de la historia: deporte guanche original, la lucha en el siglo XX o una figura actual del deporte autóctono.",
          "Crea tu tarjeta: título, fecha aproximada, dibujo o imagen, y 4 líneas de explicación.",
          "Publica tu tarjeta en el mural digital de la clase.",
          "Organiza tu mini jornada deportiva en casa: demuestra a tu familia la posición base, el juego del palo a cámara lenta y tu levantamiento técnico. ¡Eres embajador/a del deporte canario!",
        ],
        entrega: "Tu tarjeta del mural + foto de la mini jornada en casa.",
      },
    ],
  },

  /* ============ UP 9 ============ */
  {
    id: "up9",
    num: 9,
    titulo: "Olimpiadas Chirrimil",
    emoji: "🏅",
    tagline: "El gran evento final: todo lo aprendido, en juego.",
    trimestre: 3,
    fechas: "25 mayo – 18 junio",
    sesiones: 12,
    color: "#6366f1",
    color2: "#f59e0b",
    reto: "🌟 Reto de la unidad: diseña, organiza y celebra tus propias Olimpiadas Chirrimil en casa: pruebas, mascota, medallas, ceremonia… y mucho juego limpio.",
    justificacion: "Espacio de síntesis y aplicación de los aprendizajes de todo el curso: el alumnado pone en práctica de manera organizada y motivadora los deportes, juegos y actividades trabajados, integrando habilidades motrices, estrategias, respeto a las normas y valores de convivencia, con una mirada eco-sostenible del entorno.",
    criterios: ["3.2 Mostrar habilidades sociales, diálogo y respeto en la resolución de conflictos y ante la diversidad.", "5.1 Adaptar las acciones motrices a la incertidumbre del entorno natural y urbano de forma eficiente, segura y eco-sostenible."],
    saberes: ["Trabajo en equipo y resolución constructiva de conflictos; juego limpio.", "Realización de actividades físicas en el medio natural y urbano.", "Cuidado del entorno próximo durante la práctica de actividad física."],
    productos: ["Encuesta sobre reglamento", "Evento escolar"],
    actividades: [
      {
        id: "a1", titulo: "Enciende la llama: repaso olímpico", fase: "activacion", duracion: "30 min",
        inteligencias: ["intra", "ling", "logi"],
        video: "pRpeEdMmmQ0",
        desc: "Toda olimpiada empieza encendiendo la llama. La tuya se enciende repasando tu curso: verás un vídeo sobre el espíritu olímpico y harás inventario de TODO lo que has aprendido desde septiembre. Te sorprenderá la lista.",
        pasos: [
          "Ve el vídeo sobre los valores olímpicos: excelencia, amistad y respeto.",
          "Haz tu «mochila del curso»: escribe al menos una cosa aprendida en cada unidad (¡son 8!).",
          "Elige las 5 pruebas que más disfrutaste del curso: serán candidatas para tus olimpiadas.",
          "Escribe tu juramento olímpico personal: «Prometo participar con…» (complétalo con tus 3 valores).",
        ],
        entrega: "Tu mochila del curso (8 aprendizajes) + tus 5 pruebas candidatas + tu juramento.",
      },
      {
        id: "a2", titulo: "Así se organiza un gran evento", fase: "demostracion", duracion: "30 min",
        inteligencias: ["logi", "inter", "espa"],
        video: "9bZkp7q19f0",
        desc: "Detrás de unas olimpiadas hay organizadores, jueces, calendarios y logística. En el vídeo verás cómo se monta un evento deportivo. Tú serás el Comité Olímpico de tu casa: aprende a planificar como un profesional.",
        pasos: [
          "Ve el vídeo y apunta los 4 elementos de todo evento: pruebas, participantes, espacios/horarios y premios.",
          "Estudia el plano de tu casa/parque cercano y decide dónde iría cada prueba.",
          "Crea el programa oficial: 5 pruebas elegidas, orden, duración y material de cada una.",
          "Reparte roles para el gran día: ¿quién será juez? ¿quién hace de speaker? ¿quién fotografía?",
        ],
        entrega: "Tu programa oficial del evento con pruebas, horarios, espacios y roles.",
      },
      {
        id: "a3", titulo: "La encuesta del reglamento", fase: "aplicacion", duracion: "35 min",
        inteligencias: ["logi", "ling"],
        video: "YQHsXMglC9A",
        desc: "Un buen reglamento se construye escuchando. Crearás una encuesta digital (Google Forms, con ayuda de Classroom) sobre las reglas de tus olimpiadas y se la pasarás a tu familia y a 3 compañeros/as de clase. Los datos decidirán.",
        pasos: [
          "Escribe 5 preguntas de encuesta (ej.: ¿cuántos puntos debe valer el primer puesto?, ¿debe haber prueba cooperativa obligatoria?, ¿qué premio prefieres?).",
          "Crea la encuesta en Google Forms con ayuda de un adulto o desde Classroom.",
          "Envíala a tu familia y a 3 compañeros/as. Consigue al menos 5 respuestas.",
          "Analiza los resultados y redacta el reglamento final: 6 reglas aprobadas «por votación popular».",
        ],
        entrega: "Enlace o capturas de tu encuesta con las respuestas + tu reglamento final de 6 reglas.",
      },
      {
        id: "a4", titulo: "Pruebas olímpicas en el entorno", fase: "aplicacion", duracion: "45 min",
        inteligencias: ["natu", "corp"],
        video: "60ItHLz5WEA",
        desc: "Las olimpiadas Chirrimil se disputan también al aire libre: parque, plaza o playa 🏖️ (acompañado/a de un adulto). Adaptarás 2 de tus pruebas al entorno exterior con una regla de oro: dejarlo MÁS limpio de lo que estaba.",
        pasos: [
          "Elige 2 pruebas de tu programa y adáptalas al espacio exterior (ej.: circuito de agilidad entre árboles, puntería con materiales naturales… sin dañar nada).",
          "Antes de empezar: observa el entorno y detecta riesgos (suelo irregular, zonas de paso) como buen detective del riesgo.",
          "Realiza las 2 pruebas y cronometra o puntúa los resultados.",
          "Compromiso eco: recoge tu material Y algún residuo que encuentres (con precaución). Foto del «entorno mejor que antes».",
        ],
        entrega: "Resultados de tus 2 pruebas exteriores + foto del compromiso eco.",
      },
      {
        id: "a5", titulo: "Mascota, medallas y ceremonia", fase: "aplicacion", duracion: "45 min",
        inteligencias: ["espa", "musi", "ling"],
        video: "CevxZvSJLk8",
        desc: "Unas olimpiadas sin mascota no son olimpiadas. Diseña la mascota Chirrimil, fabrica las medallas con material reciclado y prepara la ceremonia: música de entrada, presentación de atletas y entrega de premios. El arte también compite.",
        pasos: [
          "Diseña y dibuja tu mascota olímpica (ponle nombre e historia: ¿de qué isla viene?).",
          "Fabrica medallas recicladas: cartón, papel de aluminio, tapones, lana… Oro, plata, bronce y la especial «Juego Limpio».",
          "Elige la música de la ceremonia y prepara la presentación de cada atleta (¡como un speaker de verdad!).",
          "Ensaya el desfile inaugural y el podio.",
        ],
        entrega: "Foto de tu mascota con su historia + foto de las medallas fabricadas.",
      },
      {
        id: "a6", titulo: "¡Olimpiadas Chirrimil: el gran día!", fase: "integracion", duracion: "90 min + evento",
        inteligencias: ["inter", "corp", "intra"],
        video: "OPf0YbXqDm0",
        desc: "El momento que llevas todo el curso preparando: celebra tus Olimpiadas Chirrimil con tu familia. Desfile, juramento, 5 pruebas, medallas y ceremonia de clausura. Después, tu última misión del curso: la reflexión final de atleta.",
        pasos: [
          "Celebra el evento completo siguiendo tu programa: desfile + juramento + pruebas + podio.",
          "Aplica tu reglamento votado y entrega la medalla al Juego Limpio con discurso incluido.",
          "Documenta el evento: fotos y clips cortos de cada prueba.",
          "Reflexión final del curso (¡tu última entrega!): ¿de qué logro estás más orgulloso/a este año? ¿Qué le dirías al alumno o alumna que eras en septiembre?",
        ],
        entrega: "Álbum del evento (fotos/vídeo) + tu reflexión final del curso.",
      },
    ],
  },
];

// ---- Info del método (página ¿Cómo aprendemos?) ----
const METODO = {
  merrill: {
    titulo: "Los Primeros Principios de Instrucción (M. David Merrill)",
    intro: "Cada unidad se organiza alrededor de un reto real (principio de centralidad en el problema) y sus actividades siguen las cuatro fases de Merrill. Así el aprendizaje no se queda en la pantalla: se activa, se observa, se practica y se integra en la vida diaria.",
    fases: ["activacion", "demostracion", "aplicacion", "integracion"],
  },
  gardner: {
    titulo: "Las Inteligencias Múltiples (Howard Gardner)",
    intro: "No todos aprendemos igual: hay quien aprende moviéndose, quien lo hace dibujando, contando, cantando o conversando. Cada actividad está etiquetada con las inteligencias que pone en juego, para que cada alumno y alumna encuentre su camino y también entrene los demás.",
  },
};
